lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem'
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase:      'A1b2C3d4E5_F6g7H8i9_JwtPass!'
    token_ttl:        3600
