name: Deploy to Server

on:
  push:
    branches:
      - main  # Ce workflow se déclenche sur chaque push dans la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP dependencies
        run: |
          composer install

      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit tests/FilmTest.php

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure git is installed on server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-38-118-50.eu-west-3.compute.amazonaws.com "
          if ! command -v git &> /dev/null; then
            sudo apt update && sudo apt install -y git;
          fi
          "

      - name: Deploy code to server
        if: success() # Exécuter cette étape seulement si les tests réussissent
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-38-118-50.eu-west-3.compute.amazonaws.com "
          cd /var/www/html/Cin-phoria && \
          git pull origin main
          "
